New layout ID 23 ALC255
acidanthera/AppleALC pull request #811
Opened 2022-10-26 13:35 UTC by anderson-suga

New layout ID 23 - Realtek ALC255 for Acer Aspire A515-54G

2022-10-27 09:59 UTC, goon-asuga approved these changes

2022-11-04 14:46 UTC, anderson-suga commented
@Andrey1970AppleLife Could you check and approve, please? Thanks

2022-11-04 16:29 UTC, goon-asuga reviewed
na

2022-11-04 16:33 UTC, goon-asuga approved these changes

2022-11-04 16:36 UTC, goon-asuga requested changes
na

2022-11-04 16:49 UTC, goon-asuga approved these changes

2022-11-04 23:18 UTC, goon-asuga approved these changes

2022-11-07 14:51 UTC, merged